//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuuuuuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Comment { get; set; }
    
        public virtual User User { get; set; }
    }
}
