//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuuuuuu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PodgotovkaEgzEntities1 : DbContext
    {
        private static PodgotovkaEgzEntities1 podgotovkaEgzEntities1;

        public PodgotovkaEgzEntities1()
            : base("name=PodgotovkaEgzEntities1")
        {
        }

        public static PodgotovkaEgzEntities1 GetContext()
        {
            if(podgotovkaEgzEntities1 == null)
            {
                podgotovkaEgzEntities1 = new PodgotovkaEgzEntities1();
            }
            return podgotovkaEgzEntities1;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
